transform the webhook in a BOT to have the benefit of threads
Dentrax/falco-gpt pull request #3
Opened 2023-08-09 00:05 UTC by Issif

As discussed weeks ago, to be able to link the alerts and the proposal from OpenAI to resolve them, it's better to use threads. In the current implementation, with a webhook to post the message to Slack, it wasn't possible. I updated the code base to use a Slack bot with just `chat:write` as scope.

In my tests, I also noticed issues with the ring buffer, basically some race conditions because of the lack of mutex/locks.

I preferred to replace by a battle tested queuing system (NATS) that can be embedded.

2023-08-18 08:38 UTC, Dentrax requested changes
Thank you @Issif! This is great work. Dropped some comments about improving the overall resiliency. 💙

2023-08-18 08:38 UTC, Dentrax commented on main.go
> +	flagQPH := flag.Int("qps", 10, "max queries per HOUR to OpenAI")
```suggestion
	flagQPH := flag.Int("qph", 10, "max queries per HOUR to OpenAI")
```

2023-08-18 08:38 UTC, Dentrax commented on main.go
> +	flatIgnoreOlder := flag.Int("ignore", 1, "Ignore events in queue older than X hour(s)")
```suggestion
	flagIgnoreOlder := flag.Int("ignore-older", 1, "Ignore events in queue older than X hour(s)")
```

2023-08-18 08:38 UTC, Dentrax commented on main.go
> +				payload.ThreadTS, err = slackClient.SendMessage(payload.Output, attachment, "")
FWIW, we should not do _any_ operation in `handler` func. This new structure would break _background-queue-processing_ architecture. Means that, from now, we will wait for total sum of Slack + ~Nats~ response time when we send a request to the this handler, which would cause a back-throttle.

Wrap with `do(func() error` for resiliency, if possible.

2023-08-18 08:38 UTC, Dentrax commented on main.go
> +				msg, _ := json.Marshal(payload)
```suggestion
				msg, err := json.Marshal(payload)
				if err != nil {
				  w.WriteHeader(http.StatusUnprocessableEntity)
				  w.Write([]byte(err.Error()))
				  return
			        }
```

2023-08-18 08:38 UTC, Dentrax commented on main.go
> +				natsClient.Publish("falco", msg)
Does `Publish` function returns any error?

Wrap with `do(func() error` for resiliency, if possible.

2023-08-18 08:38 UTC, Dentrax commented on main.go
> +			slackClient.SendMessage(response, nil, payload.ThreadTS)
Err handling + wrap with `do(func() error` for resiliency, if possible.

2023-08-18 14:53 UTC, Dentrax reviewed
Thanks, dropped some nits! @Issif

2023-08-18 14:53 UTC, Dentrax commented on main.go
> +					return nil
```suggestion
                                msg, err := json.Marshal(payload)
	                        if err != nil {
					return err
		                }
				if err := do(func() error {
					return natsClient.Publish("slack", msg)

```

2023-08-18 14:53 UTC, Dentrax commented on main.go
> +			attachment := slack.NewAttachment(payload)
```suggestion
		attachment := slack.NewAttachment(payload)
		if err := do(func() error {
			
```

What about this?

2023-08-18 15:01 UTC, Issif commented on main.go
> +					return nil
good catch.

2023-08-18 15:11 UTC, Dentrax approved these changes
LGTM! Thanks!

2023-09-03 10:55 UTC, Issif commented
Are you planning to merge?

2023-09-04 06:28 UTC, merged

2023-09-04 06:28 UTC, Dentrax commented
Thanks for the contribution, @Issif!